name: Python package

on: [push, pull_request]
env:
  POETRY_VERSION: 1.1.8

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.PYTHON_VERSION}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.PYTHON_VERSION}}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install poetry==${{env.POETRY_VERSION}}
        poetry install
    - name: Test
      run: |
        poetry run pytest -v
    - name: Run lint
      run: |
        poetry run black borderline.py
        poetry run mypy borderline.py
